name: Keek frontend test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install

      - name: Run test
        run: npm run test
